basic_settings:
  
  site_title: Anand Koshy 
  home_name: Anand Koshy
  favicon_image: /images/ak_favicon-512x512.png

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Work'
      url: '/'
    # - title: 'Work'
    #   url: '/project/'
    - title: 'About'
      url: '/about/'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: 'Thanks for stopping by :)'

grid_settings:
  overlay_opacity: 1
  grid_spacing: .65

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  linkedin_url: 'https://www.linkedin.com/in/anand-koshy/'
  dribbble_url: 'https://www.dribbble.com'
  github_url: 'https://www.github.com/anand-koshy'
  behance_url: ''
  deviantart_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  

color_settings:
  background_color: '#090909'
  background_alt_color: '#f4f5f6'


  text_header_color: '#eeeeee'
  text_subheader_color: '#898989'
  text_body_color: '#DEDEDE'
  text_accent_color: '#f20873'
  accent_color: '#f20873'
  border_color: '#dddddd'
  overlay_background_color: '#1A1715'
  overlay_text_color: '#eeeeee'
  overlay_subtitle_color: "#766A61"
  overlay_accent_color: '#ada0a6'
  error_color: '#D64541'
  footer_color: '#090909'
  thematic_break_color: '#786C63'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Inter:100,200,300,340,360,400,440,500,600,700,800,900" rel="stylesheet">'
  title_font: '"Inter", sans-serif'
  body_font: '"Inter", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  home_name:
    small_size: 25
    medium_size: 30
    large_size: 32
    weight: 400
    letter_spacing: -0.02
  menu:
    small_size: 50
    medium_size: 60
    large_size: 22
    weight: 360
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 20
    medium_size: 28
    large_size: 32
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 20
    medium_size: 26
    large_size: 26
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 18
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 360
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""